import Vue from 'vue';
import Icon from './Icon.vue';
import ValidatedField from './ValidatedField.vue';
import TelInput from './TelInput.vue';
import SlimSelect from './SlimSelect.vue';
import CheckBox from './CheckBox.vue';
import Switcher from './Switcher.vue';
import Radio from './Radio.vue';
import SubmitButton from './SubmitButton.vue';
import DropDown from './DropDown.vue';
import DatePicker from './DatePicker.vue';
import Spinner from './Spinner.vue';
import LangSelector from './LangSelector.vue';
import AmountPercent from './AmountPercent.vue';
import Guests from './Guests.vue';
import GuestsPrice from './GuestsPrice.vue';
import GuestsPriceMultiple from './GuestsPriceMultiple.vue';
import ImageSelector from './ImageSelector.vue';
import AvatarSelector from './AvatarSelector.vue';
import Floater from './Floater.vue';
import Tabs from './Tabs.vue';
import SearchFilter from './SearchFilter.vue';
import SortIndicator from './SortIndicator.vue';
import Pagination from './Pagination.vue';
import ProductsSelector from './ProductsSelector.vue';
import PictureSelector from './PictureSelector.vue';
import PagesSelector from './PagesSelector.vue';

Vue.component(Icon.name, Icon);
Vue.component(ValidatedField.name, ValidatedField);
Vue.component(TelInput.name, TelInput);
Vue.component(SlimSelect.name, SlimSelect);
Vue.component(CheckBox.name, CheckBox);
Vue.component(Switcher.name, Switcher);
Vue.component(Radio.name, Radio);
Vue.component(SubmitButton.name, SubmitButton);
Vue.component(DropDown.name, DropDown);
Vue.component(DatePicker.name, DatePicker);
Vue.component(Spinner.name, Spinner);
Vue.component(LangSelector.name, LangSelector);
Vue.component(AmountPercent.name, AmountPercent);
Vue.component(Guests.name, Guests);
Vue.component(GuestsPrice.name, GuestsPrice);
Vue.component(GuestsPriceMultiple.name, GuestsPriceMultiple);
Vue.component(ImageSelector.name, ImageSelector);
Vue.component(AvatarSelector.name, AvatarSelector);
Vue.component(Floater.name, Floater);
Vue.component(Tabs.name, Tabs);
Vue.component(SearchFilter.name, SearchFilter);
Vue.component(SortIndicator.name, SortIndicator);
Vue.component(Pagination.name, Pagination);
Vue.component(ProductsSelector.name, ProductsSelector);
Vue.component(PictureSelector.name, PictureSelector);
Vue.component(PagesSelector.name, PagesSelector);
